sonar.organization=jbrosi
sonar.projectKey=jbrosi_paith-notes

sonar.sources=app/api/src,app/worker/src,app/backend-shared/src,app/frontend/src
sonar.exclusions=**/vendor/**,**/node_modules/**,**/coverage/**,app/frontend/dist/**

sonar.php.coverage.reportPaths=php-coverage/app/api/coverage/clover.xml,php-coverage/app/worker/coverage/clover.xml
